#!/usr/bin/env python3
"""Deterministic workload generator for the log-aggregation task.

Emits a JSON-lines access log that is byte-identical for a given
(--lines, --seed, --minutes) triple on every machine and every CPython 3.8+.

Determinism notes
-----------------
The generator draws exclusively from ``random.Random.random()`` (the Mersenne
Twister 53-bit double, whose bit pattern is fixed by the CPython
implementation and has not changed across 3.x) and derives every field from it
using only IEEE-754 add/subtract/multiply/divide and integer truncation.  No
``randint``, no ``choice``, no ``shuffle``, no ``lognormvariate``, no ``math``
transcendentals -- those either have implementation details that have shifted
between CPython releases or route through libm, whose last-bit behaviour is
platform dependent.  The result is a file you can regenerate anywhere and
compare with ``shasum``.

Usage
-----
    python3 tools/generate_workload.py --lines 1200000 --seed 20260320 \\
        --out data/access.log

    python3 tools/generate_workload.py --lines 2000 --seed 7 \\
        --minutes 20 --out sample/sample.log

Run with --stats to print the shape of what was written (line count, byte
count, distinct sessions, malformed line count, sha256).
"""

from __future__ import annotations

import argparse
import hashlib
import random
import sys
from pathlib import Path

# ----------------------------------------------------------------- constants

LOG_DATE = "2026-03-14"
START_HOUR = 8

# (template, id_kind, weight)
#   id_kind 0 -> no id substitution
#   id_kind 1 -> %d numeric id
#   id_kind 2 -> %s 32-char lowercase hex id
ENDPOINTS = [
    ("/api/v2/orders", 0, 90),
    ("/api/v2/orders/%d", 1, 120),
    ("/api/v2/orders/%d/items", 1, 55),
    ("/api/v2/cart", 0, 80),
    ("/api/v2/cart/%d", 1, 45),
    ("/api/v2/checkout", 0, 40),
    ("/api/v2/products/%d", 1, 150),
    ("/api/v2/products/%d/reviews", 1, 60),
    ("/api/v2/users/%s", 2, 70),
    ("/api/v2/sessions/%s", 2, 35),
    ("/api/v2/search", 0, 110),
    ("/api/v1/legacy/report", 0, 25),
    ("/static/app.js", 0, 95),
    ("/static/vendor.css", 0, 65),
    ("/health", 0, 70),
    ("/metrics", 0, 30),
]

METHODS = [("GET", 74), ("POST", 16), ("PUT", 5), ("PATCH", 3), ("DELETE", 2)]

STATUSES = [(200, 780), (201, 40), (204, 25), (301, 10), (304, 45),
            (400, 30), (401, 18), (403, 12), (404, 22), (429, 8),
            (500, 7), (502, 3), (503, 2)]

REGIONS = [("us-east-1", 34), ("us-west-2", 22), ("eu-west-1", 18),
           ("eu-central-1", 12), ("ap-south-1", 9), ("sa-east-1", 5)]

# Search query strings appended to /api/v2/search. Chosen from a fixed table so
# the generated bytes stay stable; none of them contain a quote or a backslash.
QUERIES = ["?q=widget", "?q=blue+widget&page=2", "?q=cable&sort=price",
           "?page=3", "?q=hub&sort=rating&page=1", "?q=dock"]

HEXDIGITS = "0123456789abcdef"

USER_POOL = 5000
SESSION_PREFIX = "sess-"

# Malformed line templates, emitted on a fixed cadence. Every one of these must
# be rejected by the parser described in FORMAT.md.
MALFORMED = [
    # truncated JSON object
    '{"ts":"%(ts)s","endpoint":"/api/v2/orders","method":"GET","status":200,'
    '"dur_ms":41,"bytes":900,"session":"%(sid)s","user":',
    # status out of the 100..599 range
    '{"ts":"%(ts)s","endpoint":"/api/v2/orders","method":"GET","status":900,'
    '"dur_ms":41,"bytes":900,"session":"%(sid)s","user":"u-000042",'
    '"region":"us-east-1"}',
    # missing the dur_ms key
    '{"ts":"%(ts)s","endpoint":"/api/v2/cart","method":"GET","status":200,'
    '"bytes":900,"session":"%(sid)s","user":"u-000042","region":"us-east-1"}',
    # timestamp not in the required shape
    '{"ts":"2026-03-14 09:00:00","endpoint":"/api/v2/cart","method":"GET",'
    '"status":200,"dur_ms":41,"bytes":900,"session":"%(sid)s",'
    '"user":"u-000042","region":"us-east-1"}',
    # negative duration
    '{"ts":"%(ts)s","endpoint":"/health","method":"GET","status":200,'
    '"dur_ms":-3,"bytes":12,"session":"%(sid)s","user":"u-000042",'
    '"region":"us-east-1"}',
    # an extra, unexpected key
    '{"ts":"%(ts)s","endpoint":"/metrics","method":"GET","status":200,'
    '"dur_ms":9,"bytes":512,"session":"%(sid)s","user":"u-000042",'
    '"region":"us-east-1","trace":"abc"}',
    # endpoint is not a string
    '{"ts":"%(ts)s","endpoint":404,"method":"GET","status":200,"dur_ms":9,'
    '"bytes":512,"session":"%(sid)s","user":"u-000042","region":"us-east-1"}',
    # blank line
    "",
    # not JSON at all -- a stray plain-text line from another logger
    "2026-03-14 09:12:44 WARN  upstream pool exhausted, retrying in 250ms",
]

MALFORMED_EVERY = 997  # prime, so the malformed lines do not align with any bucket


# ------------------------------------------------------------------- helpers

def cumulative(table):
    """Turn [(value, weight), ...] into ([value, ...], [cum_fraction, ...])."""
    total = 0
    for _, weight in table:
        total += weight
    values = []
    bounds = []
    acc = 0
    for value, weight in table:
        acc += weight
        values.append(value)
        bounds.append(acc / total)
    bounds[-1] = 1.0
    return values, bounds


def pick(values, bounds, r):
    """Index into a cumulative table with a uniform draw. Linear on purpose:
    the tables are short and a bisect would add an import for no gain."""
    for i, edge in enumerate(bounds):
        if r < edge:
            return values[i]
    return values[-1]


def hex_id(rng, length):
    out = []
    for _ in range(length):
        out.append(HEXDIGITS[int(rng.random() * 16.0)])
    return "".join(out)


def format_ts(offset_ms):
    ms = offset_ms % 1000
    total_s = offset_ms // 1000
    sec = total_s % 60
    total_m = total_s // 60
    minute = total_m % 60
    hour = START_HOUR + total_m // 60
    return "%sT%02d:%02d:%02d.%03dZ" % (LOG_DATE, hour, minute, sec, ms)


def skewed(rng, low, high, power):
    """An integer in [low, high) skewed toward `low`. Only IEEE basic ops."""
    r = rng.random()
    if power == 2:
        r = r * r
    elif power == 3:
        r = r * r * r
    elif power == 4:
        r = r * r
        r = r * r
    return low + int((high - low) * r)


# ---------------------------------------------------------------- generation

def generate(out_path, lines, seed, minutes, progress=False):
    rng = random.Random(seed)

    endpoint_values, endpoint_bounds = cumulative(
        [(tpl, w) for tpl, _, w in ENDPOINTS])
    endpoint_kind = {tpl: kind for tpl, kind, _ in ENDPOINTS}
    method_values, method_bounds = cumulative(METHODS)
    status_values, status_bounds = cumulative(STATUSES)
    region_values, region_bounds = cumulative(REGIONS)

    window_ms = minutes * 60 * 1000

    # Active session pool. Each entry is [session_id, user_id, events_left].
    active = []
    session_counter = 0

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    malformed_written = 0
    sessions_seen = set()
    chunk = []
    chunk_bytes = 0
    digest = hashlib.sha256()
    total_bytes = 0

    with out_path.open("w", encoding="utf-8", newline="\n") as fh:
        for i in range(lines):
            # --- timestamp: monotonic drift plus jitter, so events arrive
            # slightly out of order and session ordering is not line ordering.
            base = (i * window_ms) // lines
            jitter = int(rng.random() * 6000.0) - 3000
            offset = base + jitter
            if offset < 0:
                offset = 0
            elif offset >= window_ms:
                offset = window_ms - 1
            ts = format_ts(offset)

            # --- session: reuse an active one, or open a new one.
            if not active or rng.random() < 0.12:
                session_counter += 1
                sid = SESSION_PREFIX + hex_id(rng, 12)
                uid = "u-%06d" % skewed(rng, 0, USER_POOL, 3)
                events_left = 1 + skewed(rng, 0, 30, 2)
                active.append([sid, uid, events_left])
                slot = len(active) - 1
            else:
                slot = int(rng.random() * len(active))
            entry = active[slot]
            sid, uid = entry[0], entry[1]
            entry[2] -= 1
            if entry[2] <= 0:
                active[slot] = active[-1]
                active.pop()

            if i % MALFORMED_EVERY == MALFORMED_EVERY - 1:
                template = MALFORMED[malformed_written % len(MALFORMED)]
                line = template % {"ts": ts, "sid": sid}
                malformed_written += 1
                chunk.append(line)
                chunk_bytes += len(line) + 1
                if chunk_bytes >= 4 << 20:
                    blob = "\n".join(chunk) + "\n"
                    fh.write(blob)
                    raw = blob.encode("utf-8")
                    digest.update(raw)
                    total_bytes += len(raw)
                    chunk = []
                    chunk_bytes = 0
                continue

            sessions_seen.add(sid)

            # --- endpoint
            template = pick(endpoint_values, endpoint_bounds, rng.random())
            kind = endpoint_kind[template]
            if kind == 1:
                endpoint = template % (1000 + skewed(rng, 0, 90000, 2))
            elif kind == 2:
                endpoint = template % hex_id(rng, 32)
            else:
                endpoint = template
            if template == "/api/v2/search":
                endpoint = endpoint + QUERIES[int(rng.random() * len(QUERIES))]
            elif rng.random() < 0.03:
                # A small slice of clients append a trailing slash. The two
                # forms are distinct endpoints; see FORMAT.md.
                endpoint = endpoint + "/"

            method = pick(method_values, method_bounds, rng.random())
            status = pick(status_values, status_bounds, rng.random())

            # --- duration: heavy right tail, and the legacy report is slow.
            if template == "/api/v1/legacy/report":
                dur = 200 + skewed(rng, 0, 9000, 2)
            elif template.startswith("/static/") or template in ("/health", "/metrics"):
                dur = 1 + skewed(rng, 0, 40, 3)
            else:
                dur = 3 + skewed(rng, 0, 2500, 4)
            if status >= 500:
                dur = dur + 500 + skewed(rng, 0, 4000, 2)

            # --- payload size
            if template.startswith("/static/"):
                nbytes = 20000 + skewed(rng, 0, 400000, 3)
            elif status == 204 or status == 304:
                nbytes = 0
            elif status >= 400:
                nbytes = 60 + skewed(rng, 0, 400, 2)
            else:
                nbytes = 180 + skewed(rng, 0, 60000, 4)

            region = pick(region_values, region_bounds, rng.random())

            line = (
                '{"ts":"%s","endpoint":"%s","method":"%s","status":%d,'
                '"dur_ms":%d,"bytes":%d,"session":"%s","user":"%s",'
                '"region":"%s"}'
                % (ts, endpoint, method, status, dur, nbytes, sid, uid, region)
            )
            chunk.append(line)
            chunk_bytes += len(line) + 1

            if chunk_bytes >= 4 << 20:
                blob = "\n".join(chunk) + "\n"
                fh.write(blob)
                raw = blob.encode("utf-8")
                digest.update(raw)
                total_bytes += len(raw)
                chunk = []
                chunk_bytes = 0
                if progress:
                    sys.stderr.write("\r  %d / %d lines" % (i + 1, lines))
                    sys.stderr.flush()

        if chunk:
            blob = "\n".join(chunk) + "\n"
            fh.write(blob)
            raw = blob.encode("utf-8")
            digest.update(raw)
            total_bytes += len(raw)

    if progress:
        sys.stderr.write("\r%s\r" % (" " * 40))
        sys.stderr.flush()

    return {
        "path": str(out_path),
        "lines": lines,
        "bytes": total_bytes,
        "sha256": digest.hexdigest(),
        "malformed_lines": malformed_written,
        "distinct_sessions": len(sessions_seen),
        "minutes": minutes,
        "seed": seed,
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lines", type=int, default=1200000,
                    help="number of log lines to emit (default: 1200000)")
    ap.add_argument("--seed", type=int, default=20260320,
                    help="RNG seed (default: 20260320)")
    ap.add_argument("--minutes", type=int, default=240,
                    help="width of the log time window in minutes (default: 240)")
    ap.add_argument("--out", default=None,
                    help="output path (default: <workspace>/data/access.log)")
    ap.add_argument("--stats", action="store_true",
                    help="print a JSON summary of what was written")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    if args.lines < 1:
        ap.error("--lines must be positive")
    if args.minutes < 1 or args.minutes > 15 * 60:
        ap.error("--minutes must be between 1 and 900 (the log must not cross midnight)")

    root = Path(__file__).resolve().parent.parent
    out = Path(args.out) if args.out else root / "data" / "access.log"
    if not out.is_absolute():
        out = (Path.cwd() / out).resolve()

    info = generate(out, args.lines, args.seed, args.minutes,
                    progress=not args.quiet)

    if args.stats or not args.quiet:
        import json
        sys.stderr.write(json.dumps(info, indent=2) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
